module.exports = {
  products: [
    {
      _id: "1",
      name: "Hiskywin Full Shirt Casual and Formal Wear, Navy Blue",
      category: "Shirts",
      image: "images/product-1.jpeg",
      price: 75,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt,Dark Blue",
      category: "Shirts",
      image: "images/product-2.jpeg",
      price: 70,
      brand: "Nike",
      rating: 5,
      numReviews: 51,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Shirts",
      image: "images/product-3.jpeg",
      price: 59,
      brand: "Adidas",
      rating: 4,
      numReviews: 45,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sportstyle Tricot Joggers",
      category: "Pants",
      image: "images/product-4.jpeg",
      price: 90,
      brand: "Under Armour",
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Champion Mens Graphic Powerblend Fleece Jogger",
      category: "Pants",
      image: "images/product-5.jpeg",
      price: 119,
      brand: "Champion",
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Aelfric Eden Mens Joggers Pants Long Multi-Pockets",
      category: "Pants",
      image: "images/product-6.jpeg",
      price: 85,
      brand: "Aelfric Eden",
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: "7",
      name: "Adidas Original,white-blue graphic",
      category: "Shirts",
      image: "images/product-7.jpeg",
      price: 49,
      brand: "Adidas",
      rating: 4,
      numReviews: 45,
    },
    {
      _id: "8",
      name: "Armani Plain white T-shirt",
      category: "Shirts",
      image: "images/product-8.jpeg",
      price: 99,
      brand: "Armani",
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: "9",
      name: "Louis Phillipe,Navy-Blue Blazer",
      category: "Blazer",
      image: "images/product-9.jpeg",
      price: 250,
      brand: "Louis Phillipe",
      rating: 3.5,
      numReviews: 89,
      countInStock: 2,
    },
    {
      _id: "10",
      name: "Levis, Classic Blue Jeans",
      category: "Pants",
      image: "images/product-10.jpeg",
      price: 75,
      brand: "Levis",
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: "11",
      name: "Hyskywin,Olive-green Tshirt",
      category: "Shirts",
      image: "images/product-11.jpeg",
      price: 85,
      brand: "Hyskywin",
      rating: 4.5,
      numReviews: 45,
      countInStock: 4,
    },
  ],
};
